name: myproject2
description: "Attendance Plus with WebRTC Face Recognition"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Backend & Database
  supabase_flutter: ^2.7.0
  http: ^1.1.0
  shared_preferences: ^2.0.0

  # Camera & WebRTC
  camera: ^0.11.1
  flutter_webrtc: ^1.0.0
  permission_handler: ^11.1.0

  # File & Path Management
  path_provider: ^2.1.4
  path: ^1.9.0

  # Face Recognition & ML
  google_ml_kit: ^0.18.0
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.11.0
  image: ^4.2.0

  # Utility
  ffi: ^2.1.3
  get_it: ^8.0.0
  provider: ^6.1.2
  get: ^4.6.6
  collection: ^1.19.1
  web_socket_channel: ^2.4.0
  uuid: ^4.2.1

  # Image Handling
  gal: ^2.3.1
  image_picker: ^1.1.2

  # Network & Device Info
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0

dependency_overrides:
  shared_preferences_android: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/converted_model.tflite